# Generated by Django 2.2.5 on 2020-08-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostsRates'),
        ),
    ]
