# Generated by Django 2.2.5 on 2021-01-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsRates2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField(default=0)),
                ('dislikes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='rates2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostsRates2'),
        ),
    ]
