# Generated by Django 2.2.5 on 2020-03-31 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_addons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addons',
            name='car_details',
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_addons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.AddOns'),
        ),
    ]
