# Generated by Django 2.2.5 on 2020-03-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20200331_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_addons',
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_addons',
            field=models.ManyToManyField(to='firstApp.AddOns'),
        ),
    ]
