# Generated by Django 2.2.5 on 2020-03-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_auto_20200331_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='car_addons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_addons', to='firstApp.AddOns'),
        ),
    ]
