# Generated by Django 2.2.5 on 2020-03-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_auto_20200331_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_addons',
        ),
        migrations.DeleteModel(
            name='AddOns',
        ),
    ]
