# Generated by Django 2.2.5 on 2020-03-31 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_auto_20200331_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('years_of_warranty', models.PositiveIntegerField(default=1)),
                ('finance_plan', models.CharField(default='unavailable', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstApp.CarPlan'),
        ),
    ]
