# Generated by Django 2.2.5 on 2020-04-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_auto_20200401_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstApp.CarPlan'),
        ),
    ]
