# Generated by Django 2.2.5 on 2020-04-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_auto_20200401_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
        migrations.DeleteModel(
            name='CarPlan',
        ),
    ]
