# Generated by Django 2.2.5 on 2020-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClosingStock',
            fields=[
                ('store_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('store_code', models.CharField(max_length=100)),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=500)),
                ('brand_name', models.CharField(max_length=200)),
                ('closing_stock', models.IntegerField()),
            ],
        ),
    ]
