# Generated by Django 2.2.5 on 2020-10-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_storeclosingstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='brand_name',
            new_name='BRAND_NAME',
        ),
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='closing_stock',
            new_name='CLOSING_STOCK',
        ),
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='item_code',
            new_name='ITEM_CODE',
        ),
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='item_name',
            new_name='ITEM_NAME',
        ),
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='store_code',
            new_name='STORE_CODE',
        ),
        migrations.RenameField(
            model_name='storeclosingstock',
            old_name='store_name',
            new_name='STORE_NAME',
        ),
    ]
