# Generated by Django 2.2.5 on 2020-10-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201015_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreClosingStock',
        ),
    ]
