# Generated by Django 2.2.5 on 2020-12-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='temperatue',
            new_name='temperatuer',
        ),
    ]
